export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  STATUS_UPDATE_NOT_ALLOWED: 'STATUS_UPDATE_NOT_ALLOWED',
  INVALID_OBJECT_ID: 'INVALID_OBJECT_ID',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
